version: "2.1"
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requires/testing.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requires/testing.txt
      - save_cache:
          paths:
            - ./eenv
          key: v1-dependencies-{{ checksum "requires/testing.txt" }}
      - run: ./bootstrap
      - run:
          name: run tests
          command: |
            . env/bin/activate
            nosetests
